spring:
  application:
    name: "configServer"
#  profiles:
#    active: native # ????????
  cloud:
    config:
      server:
#        native:
#          search-locations: "classpath:/config" # ?????????
#            search-locations: "file:/Users/kenny-sunhope/Documents/config" # ?????????
        git:
          uri: "https://github.com/eazybytes/eazybytes-config.git" # ??git????
          default-label: "master" # ??git?????
          timeout: 5 # ??????
          clone-on-start: true # ??????????git???????
          force-pull: true # ????????git???????
server:
  port: 8071